main: komas19.bloodsmp.plugin.Blocking
name: BloodSMP
version: 1.9.8
authors: [ Komas19 ]
description: A now public plugin for the Blood SMP Minecraft server.
api-version: 1.19
commands:
  bloodreload:
    description: Reloads the plugin
    usage: /<command>
    permission: bloodsmp.reload
  bloodver:
    description: Shows version of plugin
    usage: /<command>
    permission: bloodsmp.version
  barrier:
    description: Give yourself a barrier. Only one
    usage: /<command>
    permission: bloodsmp.barrier
permissions:
  bloodsmp.reload:
    description: Allows you to reload the plugin.
    default: op
  bloodsmp.barrier:
    description: Allows you to give a barrier to yourself
    default: op
  bloodsmp.version:
    description: Allows you to see plugin version
    default: op